/**
 * Per-document inline preview requirements — aligned to official Tylo Care letterheads.
 * Used by LandscapeInvoiceLikePreview wrappers.
 */
import { msmeDeclaration, INVOICE_PAYMENT_TERM } from '../invoiceGenerator/invoiceStorage.js';
import { QUOTATION_DECLARATION, QUOTATION_PAYMENT_TERM } from '../quotation/quotationStorage.js';
import { PROFORMA_DECLARATION, PROFORMA_PAYMENT_TERM } from '../proformaGenerator/proformaStorage.js';

const BANK_NOTE =
  'Please mention the invoice number while making payment. Any discrepancy should be communicated within 7 days of receipt.';

const BOS_BANK_NOTE =
  'Please mention the Bill of Supply number while making payment. Any discrepancy should be communicated within 7 days of receipt.';

const BOS_EXEMPT_NOTE =
  'GST Rate: NIL / EXEMPT. No GST has been charged on this supply as per the applicable provisions of the CGST Act, 2017.';

export const LANDSCAPE_DOC_CONFIGS = {
  invoice: {
    docKey: 'invoice',
    documentTitle: 'TAX INVOICE',
    docNoLabel: 'Invoice No.',
    dateLabel: 'Invoice Date',
    dueLabel: 'Due Date',
    totalLabel: 'Total Invoice Value',
    gstMode: 'taxable',
    leftPartyTitle: 'Bill To',
    rightPartyTitle: 'Ship To / Service Location',
    billNameLabel: 'Legal Name',
    shipNameLabel: 'Legal / Location Name',
    shipGstinLabel: 'GSTIN (if applicable)',
    paymentTermsTitle: 'Payment Terms & MSME Declaration',
    bankNote: BANK_NOTE,
    defaultTerms: INVOICE_PAYMENT_TERM,
    defaultDeclaration: (company) => msmeDeclaration(company),
    showGstExemptNote: false,
    showPoMeta: true,
    showPlaceOfSupply: false,
    showReverseCharge: false,
    showOriginalInvoice: false,
    showAdjustments: true,
    showTermsEditor: true,
    lineColumns: 'letterhead',
  },
  quotation: {
    docKey: 'quotation',
    documentTitle: 'QUOTATION',
    docNoLabel: 'Quotation No.',
    dateLabel: 'Quotation Date',
    dueLabel: 'Quotation Valid Until',
    totalLabel: 'Total Quotation Value',
    gstMode: 'taxable',
    leftPartyTitle: 'Bill To',
    rightPartyTitle: 'Ship To / Service Location',
    billNameLabel: 'Legal Name',
    shipNameLabel: 'Legal / Location Name',
    shipGstinLabel: 'GSTIN (if applicable)',
    paymentTermsTitle: 'Terms',
    bankNote: BANK_NOTE,
    defaultTerms: QUOTATION_PAYMENT_TERM,
    defaultDeclaration: () => QUOTATION_DECLARATION,
    showGstExemptNote: false,
    showPoMeta: true,
    showPlaceOfSupply: false,
    showReverseCharge: false,
    showOriginalInvoice: false,
    showAdjustments: false,
    showTermsEditor: true,
    lineColumns: 'letterhead',
  },
  proforma: {
    docKey: 'proforma',
    documentTitle: 'PROFORMA\nINVOICE',
    docNoLabel: 'Proforma Invoice No.',
    dateLabel: 'Proforma Date',
    dueLabel: 'Valid Until',
    totalLabel: 'Total Estimated Value',
    gstMode: 'taxable',
    leftPartyTitle: 'Bill To',
    rightPartyTitle: 'Ship To / Service Location',
    billNameLabel: 'Legal Name',
    shipNameLabel: 'Legal / Location Name',
    shipGstinLabel: 'GSTIN (if applicable)',
    paymentTermsTitle: 'Terms',
    bankNote: BANK_NOTE,
    defaultTerms: PROFORMA_PAYMENT_TERM,
    defaultDeclaration: () => PROFORMA_DECLARATION,
    showGstExemptNote: false,
    showPoMeta: true,
    showPlaceOfSupply: false,
    showReverseCharge: false,
    showOriginalInvoice: false,
    showAdjustments: false,
    showTermsEditor: true,
    lineColumns: 'letterhead',
  },
  'bill-of-supply': {
    docKey: 'bill-of-supply',
    documentTitle: 'BILL OF SUPPLY',
    docNoLabel: 'Bill of Supply No.',
    dateLabel: 'Bill of Supply Date',
    dueLabel: 'Due Date',
    totalLabel: 'Total Bill Value',
    gstMode: 'nil',
    leftPartyTitle: 'Bill To',
    rightPartyTitle: 'Ship To / Service Location',
    billNameLabel: 'Legal Name',
    shipNameLabel: 'Legal / Location Name',
    shipGstinLabel: 'GSTIN (if applicable)',
    paymentTermsTitle: 'Terms',
    bankNote: BOS_BANK_NOTE,
    defaultTerms:
      'Payment is due within 30 days from the date of the Bill of Supply unless otherwise agreed.',
    defaultDeclaration: (company) =>
      `${BOS_EXEMPT_NOTE} ${typeof company === 'object' ? msmeDeclaration(company) : msmeDeclaration()}`,
    showGstExemptNote: true,
    showPoMeta: true,
    /** Header block: BoS date + due from approval; PO/WO + project editable. */
    metaLayout: 'bos-header',
    datesFromApproval: true,
    showPlaceOfSupply: false,
    showReverseCharge: false,
    showOriginalInvoice: false,
    showAdjustments: false,
    showTermsEditor: true,
    lineColumns: 'letterhead',
  },
  'credit-note': {
    docKey: 'credit-note',
    documentTitle: 'CREDIT NOTE',
    docNoLabel: 'Credit Note No.',
    dateLabel: 'Credit Note Date',
    dueLabel: 'Due Date',
    totalLabel: 'Total Credit Note Value',
    gstMode: 'taxable',
    leftPartyTitle: 'Bill To',
    rightPartyTitle: 'Ship To / Service Location',
    billNameLabel: 'Legal Name',
    shipNameLabel: 'Legal / Location Name',
    shipGstinLabel: 'GSTIN (if applicable)',
    paymentTermsTitle: 'Payment Terms',
    bankNote: BANK_NOTE,
    defaultTerms: 'This Credit Note adjusts the referenced Tax Invoice as per the reason stated.',
    defaultDeclaration: () =>
      'This Credit Note is issued against the Tax Invoice referenced above in accordance with the applicable provisions of the CGST Act, 2017 and the applicable GST laws.',
    showGstExemptNote: false,
    showPoMeta: true,
    showPlaceOfSupply: false,
    showReverseCharge: false,
    showOriginalInvoice: true,
    originalRefField: 'cnReference',
    reasonField: 'creditReason',
    reasonLabel: 'Reason for Credit Note',
    showReasonOnPreview: false,
    lockOriginalInvoiceDate: true,
    showAdjustments: false,
    showTermsEditor: false,
    lineColumns: 'letterhead',
  },
  'debit-note': {
    docKey: 'debit-note',
    documentTitle: 'DEBIT NOTE',
    docNoLabel: 'Debit Note No.',
    dateLabel: 'Debit Note Date',
    dueLabel: 'Due Date',
    totalLabel: 'Total Debit Note Value',
    gstMode: 'taxable',
    leftPartyTitle: 'Bill To',
    rightPartyTitle: 'Ship To / Service Location',
    billNameLabel: 'Legal Name',
    shipNameLabel: 'Legal / Location Name',
    shipGstinLabel: 'GSTIN (if applicable)',
    paymentTermsTitle: 'Payment Terms',
    bankNote: BANK_NOTE,
    defaultTerms: 'This Debit Note adjusts the referenced Tax Invoice as per the reason stated.',
    defaultDeclaration: () =>
      'This Debit Note is issued against the original Tax Invoice referenced above under the applicable provisions of the CGST Act, 2017.',
    showGstExemptNote: false,
    showPoMeta: true,
    showPlaceOfSupply: false,
    showReverseCharge: false,
    showOriginalInvoice: true,
    originalRefField: 'dnReference',
    reasonField: 'debitReason',
    reasonLabel: 'Reason for Debit Note',
    showReasonOnPreview: false,
    lockOriginalInvoiceDate: true,
    showAdjustments: false,
    showTermsEditor: false,
    lineColumns: 'letterhead',
  },
};
